### ISSUE TITLE
Place a block and it disappeared, fabric 1.20.1

### ISSUE THREAD

**Issue by Hitman2795** [immortius/chunkbychunk#117]
[https://www.curseforge.com/minecraft/mc-mods/chunk-by-chunk/comments](url)
Comment name: Fernandes27, comment time: Feb 16, 2024
I'm bad at programming, not sure if those are the right logs to look at.
The first one is the log from my server,
[2024-02-16-7.log](https://github.com/immortius/chunkbychunk/files/14317584/2024-02-16-7.log)
And the second one is the latest log from my client.
[latest.log](https://github.com/immortius/chunkbychunk/files/14317587/latest.log)
Hope that helps :)

**Comment by immortius** [comment]
Well, I'm not seeing any relevant erros in the logs, and trying some of the mods you are using with Chunk By Chunk hasn't replicated the issue yet. I do note some of the mods you are using are old versions, and in a couple of cases target 1.20 rather than 1.20.1 (e.g. armor_visbility, ash api) so you might want to review that. I'll keep trying to replicate.

**Comment by Hitman2795** [comment]
I tried updated all the mods, and I ran a new server on my own device, haven't try play on the original server yet, but it works fine on my end. Like you said, maybe this mod have conflict with other old version mods, IDK.
