### ISSUE TITLE
Prevent mod from changing existing worlds to chunk by chunk

### ISSUE THREAD

**Issue by ghost** [immortius/chunkbychunk#122]
If the mod is loaded then a normal world is loaded, that world will have it's worldgen settings changed to Chunk by Chunk, possibility causing new chunks to never generate (at least, this is what happened when I tested this on 1.18.2).
Somewhat related to #104.

**Comment by immortius** [comment]
You can disable chunk by chunk in its mod settings before loading an existing world for the first time if you don't want chunk by chunk applied to it, or edit the chunk by chunk config file in that world manually. There's not much else that can be done from the mod's end, because there is no difference between loading a new world or an existing world from a code perspective.

I would suggest if you are intending to play a mixture of different worlds with different mods that you use a mod launcher that supports multiple profiles, like Prism, which will let you have one profile with chunk by chunk and another without.

Otherwise this is working as intended.
