### ISSUE TITLE
Unstable Chunk Spawner doesn't change biome

### ISSUE THREAD

**Issue by Partonetrain** [immortius/chunkbychunk#17]
Using an Unstable Chunk Spawner doesn't change the biome of the generated chunk; 
![image](https://user-images.githubusercontent.com/19861808/192857077-13072d85-f32a-45e9-b2fc-ad52ad65e7ab.png)
This can cause unexpected behaviors such as Snow Golems not melting in hot biomes.
![image](https://user-images.githubusercontent.com/19861808/192858085-d2f8140c-3949-4bd7-b905-9bad5c53e8ed.png)

**Comment by immortius** [comment]
This is... currently working as intended, if only because I didn't think too heavily about it. Spawning a random chunk is congruent with manually building that chunk in that area - if you build a snow palace in the middle of a desert it doesn't make it into a snow biome. The climate of an area is independent of what chunks you place there, and reflects the 'true' world.

However it is in principle possible to set up a system to override biomes on a chunk by chunk basis and persist those overrides... This would be particularly desirable given a system for spawning chunks from specific biomes, which is something I'm considering for the next wave of enhancements - no timing on that though because I'm concentrating on other projects currently.

**Comment by immortius** [comment]
Implemented in 1.9.0, for both unstable chunk spawners and the new themed chunk spawners.
