### ISSUE TITLE
[BUG] 1.18.2 some blocks built over unloaded chunks disappear while others stay upon loading chunks

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#32]
Hi. I've built a cherry tree using Biomes 'O Plenty Sakura leaves and cherry logs from Oh the Biomes you will go. I built a platform with Skylight lanterns under Glass blocks filled with water below that construction. I did that before un-petrifying the bedrock chunks. 
For some reason, the Sakura leaves get deleted but everything else stays (except some water source blocks... eh... weird). I made a backup before loading the chunk because I had cobblestone from my monster farm get deleted prior to that. 

Can you add a config to disable overwriting existing structures that were player-built if the loaded elements are low priority like air, tree leaves, dynamic tree branches, logs, etc? 
I cannot load those chunks now without having to restore hours worth of work. It seems to be connected to the block heights or something because other tree parts on lower chunks were fine. I can understand overwriting things when it's for example the end portal or a villager house, etc. But my precious tree doesn't want to go baldy :(

I hope this can be fixed soon so I can continue playing 🙏 

If you need further info, let me know. 

![grafik](https://user-images.githubusercontent.com/106652912/204158227-677fc700-70ba-4b9b-af03-b11b72fdfcad.png)

**Comment by immortius** [comment]
The current block replacement rules when spawning a chunk are to replace:
- Leaves
- Air
- All Liquids
- Bedrock (for some reason)
- Cobblestone

The liquids and cobblestone were specifically because lava and water tends to spill out of the sides of blocks, and sometimes combines into cobblestone in the adjacent block.

I think on reflection I'ld be pretty happy to drop leaves and cobblestone from the list. Having a configurable list is a good idea too.

**Comment by xFirefalconx** [comment]
Thank you, yeah that liquid one sounds reasonable. It can be replaced quite easily with a few water buckets, after all.
