### ISSUE TITLE
Game Crash on World Load

### ISSUE THREAD

**Issue by Onemario1234** [immortius/chunkbychunk#56]
[crash-2023-02-19_00.33.25-server.txt](https://github.com/immortius/chunkbychunk/files/10776448/crash-2023-02-19_00.33.25-server.txt)
[latest.log](https://github.com/immortius/chunkbychunk/files/10776449/latest.log)

My game keeps crashing when loading into the world, and according to the latest.log, it only happens when spawning me. At least, that's what I could gather. What's going on?

EDIT: Tried to start a file with Chunk by Chunk not installed and got the exact same bootstrap error. Absolutely no idea what's happening.

**Comment by immortius** [comment]
This appears to be a Somnia Awoken issue rather than a chunk by chunk issue on first read - likely your Somnia Awoken configuration is malformed (check the sideEffectStages section of the somnia-common.toml file, it should be a list of lists of the form [number, number, id, number, number], but you seem to have a number where the id should be for one of them).

**Comment by Onemario1234** [comment]
Really? Huh. I have no idea how that happened.

**Comment by Onemario1234** [comment]
What do I put in the ID section, then? Not sure what to do with that.

**Comment by Onemario1234** [comment]
Wait hold on, I was able to set those back to the recommended with Configured. Should solve the issue, let me check.

**Comment by Onemario1234** [comment]
Yep, it's working now. Thanks for letting me know the issue!
