### ISSUE TITLE
Spawner incompatibility with Dynamic trees on 1.18.2

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#64]
Hiya, me again. 
I tested a few CBC functions on my modpack just now, and for an unknown reason, the spawners that change the to be spawned biome (example you're on plains and choose to spawn a forest biome) doesn't spawn trees, even if it's supposed to do so. 
What is spawning, are specific tree pieces like Quark ones. No oaks though. When restoring chunks from the overworld, this is not happening. 
Since I am using dynamic trees, is there a chance they don't get properly replaced? I haven't used the feature before so I only notice this now. Let me know if you need any specific info. 
CBC 1.13.2
Forge 40.2.0
Dynamic trees: 
DynamicTrees-1.18.2-0.11.0-Beta10.1
DynamicTreesBOP-1.18.2-3.0.0-Beta3
DynamicTreesQuark-1.18.2-2.2.3
DynamicTreesPlus-1.18.2-0.2.0-Beta4

I also feel like in some cases it would be great to be able to use the biome changer blocks again, not just once. So for example, changed plains to desert, changed adjacent block to forest, where you have one floating dynamic tree branch, you decide you change the desert to forest, instead.

**Comment by immortius** [comment]
Looks like terrablender is injecting its biomes into all the biome-specific dimensions used by the themed chunk spawners. I'll see if there is something I can do to exclude them.

I have been considering adding some tools/blocks/something for specifying biomes for specific regions - so for example allowing the creation of a warm ocean terrarium or similar. In terms of respawning a chunk, I'ld have to make some sort of chunk annihilator so that it can be respawned.
