### ISSUE TITLE
[1.20.1] Chest doesn't spawn when certain settings are changed

### ISSUE THREAD

**Issue by Peach774** [immortius/chunkbychunk#82]
I changed the spawn chest to not be initial chunk only and changed the chest contents to world core, and there is no chest in my initial chunk so I'm stuck. What I wanted to happen and expected to happen, is every chunk would have a chest at y-60 (as the config says and is the default setting), with a world core in it. Did I do something wrong?

**Comment by immortius** [comment]
That is how it should work, yes. And I just quickly tested with 1.19.3 Forge version and that seemed to be working. There is one more setting - Spawn chunk chest - which also has to be set to Yes, was that the case? Otherwise could you provide some more information on the exact minecraft version and loader?

**Comment by Peach774** [comment]
> 

So that confirms it as a 1.20.1 issue? Good to know.

**Comment by immortius** [comment]
Addressed in 2.1.0
