### ISSUE TITLE
Dimension Mod Sync

### ISSUE THREAD

**Issue by Peach774** [immortius/chunkbychunk#85]
Would be nice to have the chunks be able to start at the same start amount or synced to the overworld for other dimensions like Twilight Forest. Is this possible?

**Comment by immortius** [comment]
There are some options in the [Sky Dimension Data](https://github.com/immortius/chunkbychunk/wiki/Sky-Dimension-Data) format around synching. From memory twilight forest is scaled to be larger than the overworld, which means I don't allow synching it to the overworld (since every overworld chunk results in 64 twilight forest chunks or similar). The number of initial chunks can also be specified.  There's no option to have the initial chunks the same as the value configured for the overworld though.

**Comment by Peach774** [comment]
> There are some options in the [Sky Dimension Data](https://github.com/immortius/chunkbychunk/wiki/Sky-Dimension-Data) format around synching. From memory twilight forest is scaled to be larger than the overworld, which means I don't allow synching it to the overworld (since every overworld chunk results in 64 twilight forest chunks or similar). The number of initial chunks can also be specified. There's no option to have the initial chunks the same as the value configured for the overworld though.

Well my problem is that right now the Twilight Forest doesn't limit chunks at all and I need it to do so.

**Comment by immortius** [comment]
Ah, well define a Sky Dimension Data for it. Twilight forest was the test scenario I used for that feature actually.

**Comment by Peach774** [comment]
> Ah, well define a Sky Dimension Data for it. Twilight forest was the test scenario I used for that feature actually.

What do you name the actual json file?

**Comment by immortius** [comment]
Anything you'ld like. I would generally name it after the dimension it is apply to.
